"""add new fields in invite token

Revision ID: ce43c66a36c9
Revises: e440f5abd4f2
Create Date: 2026-02-25 15:29:29.285666

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce43c66a36c9'
down_revision: Union[str, Sequence[str], None] = 'e440f5abd4f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invite_token', sa.Column('token', sa.String(), nullable=True))
    op.add_column('invite_token', sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False))
    op.create_index(op.f('ix_invite_token_token'), 'invite_token', ['token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_invite_token_token'), table_name='invite_token')
    op.drop_column('invite_token', 'expires_at')
    op.drop_column('invite_token', 'token')
    # ### end Alembic commands ###
